description: > # this means to ignore newlines until "show_excerpts:"
  Tri Bui (buitri84) home on the Internet...

theme: minima

minima:
  date_format: "%d %-b %-Y"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

